#!/usr/bin/python3
import cv2
img=cv2.imread('download.jpg',1)
cv2.imshow('download.jpg',img)
#to display black & white image
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('live',gray)
cv2.waitKey()

cv2.destroyAllWindows()
