#!/usr/bin/python3
import cv2
cap=cv2.VideoCapture(0)
while cap.isOpened():
	status,frame=cap.read()
	#detecting blue color
	bluimg=cv2.inRange(frame,(0,0,0),(255,50,50))
	cv2.imshow('Liveblueimg',bluimg)
	if cv2.waitKey(10) & 0xff==ord('q'):
		break
cv2.destroyAllWindows()
cap.release()
